name: Verificar formato de código

on:
  pull_request:
    paths:
      - '**/*.cs'
      - '.editorconfig'

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar SDK de .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # O la versión que uses

      - name: Restaurar dependencias
        run: dotnet restore WebApplication1.sln

      - name: Verificar formato
        id: checkFormatting
        run: |
          dotnet format WebApplication1.sln --verify-no-changes --verbosity detailed
