name: Verificar formato de código

on:
  pull_request:
    paths:
      - '**/*.cs'
      - '.editorconfig'

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Verificar formato
        continue-on-error: true
        id: checkFormatting
        run: |
          dotnet format WebApplication1.sln
