name: Run .NET Formatter

on:
  pull_request:
    paths:
      - '**/*.cs'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.203'

      - name: Install dotnet-format
        run: dotnet tool install --global dotnet-format

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Check dotnet-format version
        run: dotnet tool list --global

      - name: Run dotnet-format
        run: dotnet format --verify-no-changes --verbosity diagnostic
